% quit_options

h_del_fig = fullscreenfigure;
set(h_del_fig, 'Name', 'FormantMeasurer', 'NumberTitle', 'off');

del_all = true;
del_processed = false;
del_none = false;
save_pos = false;

Bgroup=uibuttongroup('Title','Quit Options',...
                        'FontSize',12,...
                        'Units','normalized',...
                        'Position',[.2 .4 .6 .4]);
Bdel_all = uicontrol('Style','Radio',...
                        'String','Delete all temporary format-track files',...
                        'Value',del_all,...
                        'Units','normalized',...
                        'Position',[.1 .7 .8 .1],...
                        'Parent', Bgroup);
Bdel_processed = uicontrol('Style','Radio',...
                        'String','Keep temporary format-track files for unchecked vowels',...
                        'Value',del_processed,...
                        'Units','normalized',...
                        'Position',[.1 .6 .8 .1],...
                        'Parent', Bgroup);
Bdel_none = uicontrol('Style','Radio',...
                        'String','Keep all temporary format-track files',...
                        'Value',del_none,...
                        'Units','normalized',...
                        'Position',[.1 .5 .8 .1],...
                        'Parent', Bgroup);
Bsave_pos = uicontrol('Style','Check',...
                        'String','Save position of windows',...
                        'Value',save_pos,...
                        'Units','normalized',...
                        'Position',[.1 .2 .8 .1],...
                        'Parent', Bgroup);
% next button
button_next;
while nextb<=nextb_ref
    pause(0.1)
end

del_all = get(Bdel_all, 'Value');
del_processed = get(Bdel_processed, 'Value');
del_none = get(Bdel_none, 'Value');
save_pos = get(Bsave_pos, 'Value');

delete(h_del_fig);
