%function button_next

%closes current figure

replaybutton = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.7 .0 .1 .1], ...
      'FontSize',10, ...
      'String','P');
    set(replaybutton,'Callback','global replay; replay=1; %clear replay')
  
%return