%function button_next

%closes current figure

redobutton = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.9 .0 .1 .1], ...
      'FontSize',10, ...
      'String','R');
    set(redobutton,'Callback','gloal goodrecording cont; goodrecording=0; cont=1; %clear goodrecording cont')
  
%return