diffid = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.675 .05 .2 .1], ...
      'FontSize',12, ...
      'String','Choose different id');
  set(diffid,'Callback','global append; append = 0; uiresume;');
