%function button_next

%closes current figure

replaybutton = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.8 .0 .1 .1], ...
      'FontSize',10, ...
      'String','O');
    set(replaybutton,'Callback','global goodrecording cont replay; goodrecording=1; cont=1; replay=0; %clear goodrecording cont replay')
  
%return