% button_play

bappend = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.425 .05 .2 .1], ...
      'FontSize',12, ...
      'String','Append to existing files');
  s='global append RecAnswerDir; append = 1; uiresume;';
  set(bappend,'Callback',s);
