overw = uicontrol('Style','pushbutton', ...
      'Units','normalized', ...
      'Position',[.175 .05 .2 .1], ...
      'FontSize',12, ...
      'String','Overwrite existing files');
  ss='global append RecAnswerDir; append = -1; uiresume;';
  set(overw,'Callback',ss);
